/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab8;

public class Library {
	public static void main(String[] arg) {
		System.out.println("RedSox!");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
